---
# file: tasks/main.yml
# Top-level installer for multiple Oracle JDK installations.
#

  - name: Regard default java specification
    set_fact:
      java_specification_real: "{{ java_specification_defaults }}"
    when:
      - (java_specification_union_with_defaults | bool == True) or (java_specification | length == 0)

  - name: Regard custom java specification
    set_fact:
      java_specification_real: "{{ java_specification + java_specification_real | default([]) }}"
    when:
       - java_specification | length > 0

  - name: Realize multiple java installation
    include: implement.yml
    vars:
      java_version: "{{ javaspec.major }}"
      java_subversion: "{{ javaspec.minor }}"
    with_items: "{{ java_specification_real }}"
    when: java_install_multiple_versions | bool == True
    loop_control:
      loop_var: javaspec

  - name: Realize single java installation
    include: implement.yml
    when: java_install_multiple_versions | bool == False
